version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-review-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app     
    restart: unless-stopped
